/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ageofbrawls.plataforma.interfaz.editor;

import ageofbrawls.contenido.Recursos.Comida;
import ageofbrawls.contenido.Recursos.Madera;
import ageofbrawls.contenido.Recursos.Piedra;
import ageofbrawls.contenido.contenedor.Arbusto;
import ageofbrawls.contenido.contenedor.Bosque;
import ageofbrawls.contenido.contenedor.Cantera;
import ageofbrawls.contenido.edificio.Casa;
import ageofbrawls.contenido.edificio.Ciudadela;
import ageofbrawls.contenido.edificio.Cuartel;
import ageofbrawls.plataforma.Celda;
import ageofbrawls.plataforma.Civilizacion;
import ageofbrawls.plataforma.Comando;
import ageofbrawls.plataforma.Juego;
import ageofbrawls.z.excepciones.Argumentos.ExcepcionArgumentosInternos;
import ageofbrawls.z.excepciones.Recursos.ExcepcionCorrespondenciaRecursos;
import ageofbrawls.z.excepciones.noExiste.ExcepcionNoExisteArchivo;
import ageofbrawls.z.excepciones.noExiste.ExcepcionNoExisteCivilizacion;
import ageofbrawls.z.excepciones.noExiste.ExcepcionNoExisteMapa;
import ageofbrawls.z.excepciones.noExiste.ExcepcionNoExistePosicion;
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mprad
 */
public class Disenador extends javax.swing.JFrame {

    private int fila;
    private int col;
    private Comando juego;

    /**
     * Creates new form Disenador
     */
    public Disenador(Comando juego, Image icon) {
        this.juego = juego;
        initComponents();
        enableComponents(panelControles, false);
        setIconImage(icon);
        int n = JOptionPane.showConfirmDialog(
                this,
                "Crear un nuevo mapa aleatorio?",
                "Carga",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, new ImageIcon(icon));
        if (n == JOptionPane.NO_OPTION) {
            JFileChooser mapa = new JFileChooser();
            mapa.setDialogTitle("Selecciona el mapa");
            mapa.addChoosableFileFilter(new FileNameExtensionFilter("*.csv", "csv"));
            mapa.setAcceptAllFileFilterUsed(false);
            if (mapa.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                JFileChooser personajes = new JFileChooser();
                personajes.setDialogTitle("Selecciona el archivo de personajes");
                personajes.addChoosableFileFilter(new FileNameExtensionFilter("*.csv", "csv"));
                personajes.setAcceptAllFileFilterUsed(false);
                personajes.setCurrentDirectory(mapa.getCurrentDirectory());
                if (personajes.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                    JFileChooser edificios = new JFileChooser();
                    edificios.setDialogTitle("Selecciona el archivo de edificios");
                    edificios.addChoosableFileFilter(new FileNameExtensionFilter("*.csv", "csv"));
                    edificios.setAcceptAllFileFilterUsed(false);
                    edificios.setCurrentDirectory(personajes.getCurrentDirectory());
                    if (edificios.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                        juego.cargarSeparado(mapa.getSelectedFile(), edificios.getSelectedFile(), personajes.getSelectedFile());
                    }
                }
            }
        }

    }

    public void setCanvas(Canvas canvas) {

        prev.add(canvas, BorderLayout.CENTER);

    }

    public void seleccionado(int posX, int posY) {
        fila = (-posY + juego.getMapa().getFilas() - 1);
        col = posX;
        sele.setText(fila + " , " + col);
        enableComponents(panelControles, true);
        Celda c = juego.getMapa().getCelda(col, fila);
        if (c.getContenedorRec().getRecurso() != null) {
            numero.setValue(c.getContenedorRec().getRecurso().getCantidad());
        }
    }

    private void enableComponents(Container cont, boolean enable) {
        for (Component c : cont.getComponents()) {
            c.setEnabled(enable);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sele = new javax.swing.JLabel();
        panelControles = new javax.swing.JPanel();
        pradera = new javax.swing.JButton();
        cantera = new javax.swing.JButton();
        arbusto = new javax.swing.JButton();
        bosque = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        numero = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonCiudadela = new javax.swing.JButton();
        botonCasa = new javax.swing.JButton();
        botonCuartel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        exportar = new javax.swing.JButton();
        prev = new javax.swing.JPanel();
        vaciarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estudio de diseño");
        setMinimumSize(new java.awt.Dimension(800, 570));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+7f));
        jLabel1.setText("Seleccionado:");

        sele.setFont(sele.getFont().deriveFont(sele.getFont().getSize()+7f));
        sele.setText("Nada");

        panelControles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pradera.setText("Pradera");
        pradera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                praderaActionPerformed(evt);
            }
        });

        cantera.setText("Cantera");
        cantera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canteraActionPerformed(evt);
            }
        });

        arbusto.setText("Arbusto");
        arbusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arbustoActionPerformed(evt);
            }
        });

        bosque.setText("Bosque");
        bosque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosqueActionPerformed(evt);
            }
        });

        jLabel3.setText("Contenedor:");

        numero.setModel(new javax.swing.SpinnerNumberModel(50, 0, 100, 1));

        jLabel4.setText("Cantidad:");

        jLabel5.setText("Edificio:");

        botonCiudadela.setText("Ciudadela");
        botonCiudadela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCiudadelaActionPerformed(evt);
            }
        });

        botonCasa.setText("Casa");
        botonCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCasaActionPerformed(evt);
            }
        });

        botonCuartel.setText("Cuartel");
        botonCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuartelActionPerformed(evt);
            }
        });

        jLabel2.setText("Modificar celda");

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlesLayout.createSequentialGroup()
                        .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonCiudadela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelControlesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelControlesLayout.createSequentialGroup()
                        .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(bosque)
                            .addComponent(arbusto)
                            .addComponent(cantera)
                            .addComponent(pradera))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelControlesLayout.createSequentialGroup()
                        .addComponent(pradera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arbusto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bosque)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCiudadela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCasa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCuartel)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        exportar.setText("Exportar a archivo");
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });

        prev.setMinimumSize(new java.awt.Dimension(100, 100));
        prev.setLayout(new java.awt.BorderLayout());

        vaciarBoton.setText("Vaciar mapa");
        vaciarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(sele))
                                    .addComponent(panelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vaciarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(171, 171, 171)))
                        .addComponent(prev, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exportar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sele))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(vaciarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportar)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void praderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_praderaActionPerformed
        Celda c = juego.getMapa().getCelda(col, fila);
        c.setEdificio(null);
        c.hacerPradera();
    }//GEN-LAST:event_praderaActionPerformed

    private void canteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canteraActionPerformed
        try {
            Celda c = juego.getMapa().getCelda(col, fila);
            c.setEdificio(null);
            c.hacerPradera();
            c.setContenedorRecursos(new Cantera(new Piedra((Integer) numero.getModel().getValue())));
        } catch (ExcepcionArgumentosInternos | ExcepcionCorrespondenciaRecursos ex) {
            Logger.getLogger(Disenador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_canteraActionPerformed

    private void arbustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arbustoActionPerformed
        try {
            Celda c = juego.getMapa().getCelda(col, fila);
            c.setEdificio(null);
            c.hacerPradera();
            c.setContenedorRecursos(new Arbusto(new Comida((Integer) numero.getModel().getValue())));
        } catch (ExcepcionArgumentosInternos | ExcepcionCorrespondenciaRecursos ex) {
            Logger.getLogger(Disenador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_arbustoActionPerformed

    private void bosqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosqueActionPerformed
        try {
            Celda c = juego.getMapa().getCelda(col, fila);
            c.setEdificio(null);
            c.hacerPradera();
            c.setContenedorRecursos(new Bosque(new Madera((Integer) numero.getModel().getValue())));
        } catch (ExcepcionArgumentosInternos | ExcepcionCorrespondenciaRecursos ex) {
            Logger.getLogger(Disenador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bosqueActionPerformed

    private void botonCiudadelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCiudadelaActionPerformed
        try {
            Celda c = juego.getMapa().getCelda(col, fila);
            c.hacerPradera();
            Civilizacion civ = juego.getMapa().getCivilizaciones().get(juego.getActiva());
            String nombre = "ciudadela1";
            int i = 1;
            while (civ.getEdificios().containsKey("ciudadela" + i)) {
                i++;
                nombre = "ciudadela" + i;
            }
            c.setEdificio(new Ciudadela(c.getPosicion(), nombre, civ));
        } catch (ExcepcionArgumentosInternos ex) {
            Logger.getLogger(Disenador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonCiudadelaActionPerformed

    private void botonCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCasaActionPerformed
        try {
            Celda c = juego.getMapa().getCelda(col, fila);
            c.hacerPradera();
            Civilizacion civ = juego.getMapa().getCivilizaciones().get(juego.getActiva());
            String nombre = "casa1";
            int i = 1;
            while (civ.getEdificios().containsKey("casa" + i)) {
                i++;
                nombre = "casa" + i;
            }
            c.setEdificio(new Casa(c.getPosicion(), nombre, civ));
        } catch (ExcepcionArgumentosInternos ex) {
            Logger.getLogger(Disenador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonCasaActionPerformed

    private void botonCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuartelActionPerformed
        try {
            Celda c = juego.getMapa().getCelda(col, fila);
            c.hacerPradera();
            Civilizacion civ = juego.getMapa().getCivilizaciones().get(juego.getActiva());
            String nombre = "cuartel1";
            int i = 1;
            while (civ.getEdificios().containsKey("cuartel" + i)) {
                i++;
                nombre = "cuartel" + i;
            }
            c.setEdificio(new Cuartel(c.getPosicion(), nombre, civ));
        } catch (ExcepcionArgumentosInternos ex) {
            Logger.getLogger(Disenador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonCuartelActionPerformed

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
        JFileChooser dir = new JFileChooser();
        dir.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        dir.setDialogTitle("Seleccionar directorio");

        if (dir.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                juego.guardar(dir.getSelectedFile().getAbsolutePath());
            } catch (ExcepcionNoExisteArchivo ex) {
                Logger.getLogger(Disenador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_exportarActionPerformed

    private void vaciarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarBotonActionPerformed
        try {
            juego.getMapa().clear();
            juego.getMapa().addCivilizacion(juego.getActiva(), new Civilizacion(juego.getMapa(), juego.getActiva()));
        } catch (ExcepcionArgumentosInternos | ExcepcionNoExistePosicion | ExcepcionNoExisteMapa | ExcepcionNoExisteCivilizacion ex) {
            Juego.CONSOLA.imprimir(ex.getMensaje());
        }
    }//GEN-LAST:event_vaciarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arbusto;
    private javax.swing.JButton bosque;
    private javax.swing.JButton botonCasa;
    private javax.swing.JButton botonCiudadela;
    private javax.swing.JButton botonCuartel;
    private javax.swing.JButton cantera;
    private javax.swing.JButton exportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner numero;
    private javax.swing.JPanel panelControles;
    private javax.swing.JButton pradera;
    private javax.swing.JPanel prev;
    private javax.swing.JLabel sele;
    private javax.swing.JButton vaciarBoton;
    // End of variables declaration//GEN-END:variables
}
